### ISSUE TITLE
実行エラー

### ISSUE THREAD

**Issue by mage999** [tobitti0/join_logo_scp_trial#7]
/home/user/JoinLogoScpTrialSetLinux/JoinLogoScpTrialSetLinux/modules/join_logo_scp_trial/src/output/chapter_jls.js:50
      for(let r of data.match(RegExp(strRegTrim,'g'))){
                        ^

TypeError: data.match is not a function or its return value is not iterable
    at Interface.<anonymous> (/home/user/JoinLogoScpTrialSetLinux/JoinLogoScpTrialSetLinux/modules/join_logo_scp_trial/src/output/chapter_jls.js:50:25)

data.match が functionとして利用できなくなってしまったみたいなのですが、
どのように修正すればいいでしょうか？

**Comment by tobitti0** [comment]
報告ありがとうございます。
すべてのtsファイルで発生しますでしょうか？

あくまで想定ですが`obs_cut.avs`に問題がある気がします。
可能であれば、対象のresultフォルダに出力されている`obs_cut.avs`を共有していただけませんか。
平日は時間がどれるか怪しいところもありますが、可能な限り調査します。

**Comment by mage999** [comment]
ご連絡ありがとうございます。

    Reader.on("line", (data) => {
      for(let r of data.match(RegExp(strRegTrim,'g'))){
        nItemTrim.push(Number(r.match(new RegExp(strRegTrim))[1]));
        nItemTrim.push(Number(r.match(new RegExp(strRegTrim))[2]) + 1);
      }
    });

該当部分がこの部分だったので、一度コメントアウトして、テストなどをして、
obs_cut.avs を取得するために、再度コメントアウト外して実行したら、
なぜか実行できるようになってしまいました。

EPGstation v2にバージョンアップした直後に発生していたらしく、
それまでは問題なく使えていた環境だったので、何が原因で発生して、
何が要因で収まったのかが判断できない状況ですがとりあえぜ治ってしまったので、
一旦closeしてください。

お騒がせいたしました。

Twitterに挙げていた、エンコードの進行状況の連携方法、
楽しみにおまちしております。

**Comment by tobitti0** [comment]
承知しました。
もし、再発しましたら再び開くか、新しいIssueを立ててください。
よろしくお願いします。

v2での連携例の方は一週間ほど自環境で動作確認してからになるので、土曜日あたりを予定しています。
